name: Validate Gradle Wrapper
on: push
jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2